development:
  adapter: postgresql
  database: p_education_development
  host: localhost

test:
  adapter: postgresql
  database: p_education_test
  host: localhost

production:
  adapter: postgresql
  database: p_education_production
  host: localhost
